import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DEFAULTS} from '../dist/defaults.mjs';
import {parseJson,normalizePath,scopeOf,xpCurve,clone,attributePreview,mobPreview,validatePack} from '../dist/engine.mjs';
import {readZip,writeZip,crc32} from '../dist/zip.mjs';
let assertions=0;const equal=(a,b,msg)=>{assert.deepEqual(a,b,msg);assertions++},throws=(f,p)=>{assert.throws(f,p);assertions++};
const s=DEFAULTS['config/ras/settings.json'],rows=xpCurve(s);
for(const [l,xp,total] of [[1,140,140],[2,190,330],[3,250,580],[25,4100,41500],[50,14350,264250],[75,30850,824500],[99,52570,1824900],[100,53600,1878500],[101,36062,1914562],[102,36783,1951345]]){equal(rows[l-1].xp,xp,'XP '+l);equal(rows[l-1].total,total,'cumulative '+l)}
const f=clone(s);f.exp_required_per_level=[];const fallback=xpCurve(f);for(const [l,xp] of [[2,154],[3,169],[25,1381],[26,1519],[50,7706],[51,8245],[75,21135],[76,21980],[100,35355]])equal(fallback[l-1].xp,xp,'fallback '+l);
equal(xpCurve({})[0].xp,1,'strict imported missing fields return runtime zeros then clamped');
throws(()=>parseJson('{"a":1,"a":2}'),/Duplicate/);throws(()=>parseJson('{"a":{"x":1,"x":2}}'),/Duplicate/);throws(()=>parseJson('{"a":9007199254740993}'),/precision/);throws(()=>parseJson('{"a":1e999}'),/finite/);throws(()=>parseJson('[]'),/object/);throws(()=>parseJson('{"x":null}junk'),/Unexpected/);equal(parseJson('{"__proto__":{"safe":true}}').__proto__.safe,true,'preserve proto-shaped key without merging');equal({}.safe,undefined,'no pollution');
for(const p of ['../settings.json','/config/ras/settings.json','config/ras/../../bad.json','config\\ras\\settings.json','C:/config/ras/settings.json','config/ras/./x.json','config/ras//x.json'])throws(()=>normalizePath(p),/Unsafe|Unsupported/);
equal(normalizePath('ras/display/settings.json'),'config/ras/display/settings.json');equal(scopeOf('config/ras/display/overlay.json'),'client');equal(scopeOf('config/ras/settings.json'),'server');
const a=clone(DEFAULTS['config/ras/attributes/attribute_2.json']);equal(attributePreview(a,5).value,2);a.cmd_to_exc=['/say hello','/attribute @s minecraft:attack_damage base set [param(10)]'];equal(attributePreview(a,5).valueForCommand,2,'first nonblank command controls effective param');
const sharedFixture=new URL('../../../tests/fixtures/mob-xp-contract.json',import.meta.url),localFixture=new URL('./mob-xp-contract.json',import.meta.url);const cases=JSON.parse(fs.readFileSync(fs.existsSync(sharedFixture)?sharedFixture:localFixture)).cases,results=[];for(const c of cases){const ctx=c.context,r=mobPreview(c.config,{default_vp_rates:ctx.effective_rate},{entity:ctx.entity,tags:ctx.tags,health:ctx.max_health,armor:ctx.armor,difficulty:ctx.difficulty});try{equal(r.total,c.expected_vp,c.name);equal(r.rule==='Legacy health basis'?null:r.rule,c.expected_rule,c.name+' winner');results.push({name:c.name,pass:true})}catch(e){results.push({name:c.name,pass:false,got:r.total,expected:c.expected_vp});throw e}}
const original='{"max_player_level":12, "custom": {"note":"<script>bad()</script>", "arr":[3,1,2]}, "exp_curve_max_level":12}\n';const files={'config/ras/settings.json':original,'config/ras/extra_custom.json':'{"enabled":false,"unknown":["b","a"]}\n','config/ras/readme.txt':'Supporting file stays untouched.'};const zip=writeZip(files);const restored=await readZip(zip);for(const [p,text] of Object.entries(files))equal(new TextDecoder().decode(restored[p]),text,'byte roundtrip '+p);equal(crc32(new TextEncoder().encode('123456789')),0xcbf43926,'standard CRC32 vector');
const changed=parseJson(original);changed.max_player_level=15;const second=await readZip(writeZip({...files,'config/ras/settings.json':JSON.stringify(changed)}));equal(parseJson(new TextDecoder().decode(second['config/ras/settings.json'])).custom,parseJson(original).custom,'unknown key/array unchanged after known edit');
const bad=zip.slice();bad[35]^=1;await assert.rejects(()=>readZip(bad),/Invalid|integrity|disagree|Unsupported|Duplicate/);assertions++;
equal(validatePack(DEFAULTS).errors,[],'fresh defaults validate');
fs.mkdirSync(new URL('../test-results/',import.meta.url),{recursive:true});fs.writeFileSync(new URL('../test-results/engine-results.json',import.meta.url),JSON.stringify({assertions,mobCases:results,sourceXPVectors:'passed',storedZIPRoundtrip:'passed',jsonSafety:'passed'},null,2));
console.log(JSON.stringify({assertions,mobCases:cases.length,result:'passed'}));
const mobConfig=clone(cases[3].config);mobConfig.unknown_extension={preserve:true};mobConfig.rules[0].custom_note='preserved';const exports=writeZip({'config/ras/mob_xp.json':JSON.stringify(mobConfig,null,2)+'\n'});fs.writeFileSync(new URL('../test-results/mob-xp-builder-export.zip',import.meta.url),exports);fs.writeFileSync(new URL('../test-results/mob-xp-builder-export.json',import.meta.url),JSON.stringify(mobConfig,null,2)+'\n');
