import assert from 'node:assert/strict';
import {DEFAULTS} from '../dist/defaults.mjs';
import {clone,parseJson,scopeOf,xpCurve,attributePreview,effectiveDimensionRate,mobPreview,validatePack,patchRootJson,setOptionalNumber,attributePathInfo} from '../dist/engine.mjs';
let checks=0;const eq=(a,b,name)=>{assert.deepEqual(a,b,name);checks++};const valid=c=>validatePack({'config/ras/mob_xp.json':c},{allowMob:true}).errors;
eq(valid({schema_version:1}),[],'Omitted optional mob objects/fields accepted');eq(valid({schema_version:1,enabled:true,difficulty_weighting:{},armor_weighting:{enabled:true,per_armor_point:.1},rules:[]}),[],'Partial weighting object uses runtime defaults');
const ctx={entity:'minecraft:zombie',health:20,armor:2.5,difficulty:'hard'},drop={default_vp_rates:1.5};eq(mobPreview({schema_version:1,enabled:true,armor_weighting:{enabled:true,per_armor_point:.1}},drop,ctx).total,37.5,'Omitted armor cap is5');eq(mobPreview({schema_version:1,enabled:true,difficulty_weighting:{enabled:true}},drop,ctx).total,30,'Omitted difficulty table values are1');
for(const rule of [{id:' ',entity:'minecraft:zombie'},{id:'bad',entity:'minecraft:zombie',priority:2147483648},{id:'bad',entity:'minecraft:zombie',priority:-2147483649},{id:'bad',entity:'',tag:'pack:boss'},{id:'bad',entity:'minecraft:zombie',tag:'pack:boss'},{id:'bad',entity:'minecraft:zombie',base_xp:-1},{id:'bad',entity:'minecraft:zombie',enabled:null}]){eq(valid({schema_version:1,enabled:true,rules:[rule]}).length>0,true,'Invalid rule blocks builder export');eq(mobPreview({schema_version:1,enabled:true,rules:[rule]},drop,ctx).total,30,'Invalid rule skipped in runtime preview')}
eq(scopeOf('config/ras/stats_display.json'),'server','Stats display is synced server data');const a=clone(DEFAULTS['config/ras/attributes/attribute_2.json']);a.cmd_to_exc=['/attribute @s minecraft:attack_damage base set [param(foo)]'];eq(attributePreview(a,5).valueForCommand,2,'Malformed command param falls back to metadata');a.cmd_to_exc=['/attribute @s minecraft:attack_damage base set [param()]'];eq(attributePreview(a,5).valueForCommand,2,'Empty command param falls back to metadata');a.cmd_to_exc=['/attribute @s minecraft:attack_damage base set [param(100)]'];const p=attributePreview(a,20);eq(p.overCap,true,'Command result cap checked');eq(p.metadataOverCap,false,'Template metadata cap stays separate');
eq(effectiveDimensionRate({default_vp_rates:2,dimensions_drop_rates:['minecraft:overworld/bad','minecraft:overworld/9']},'minecraft:overworld'),2,'Malformed first matched rate retains global and stops');eq(effectiveDimensionRate({default_vp_rates:2,dimensions_drop_rates:['minecraft:overworld/','minecraft:overworld/9']},'minecraft:overworld'),2,'Empty dimension rate is malformed');
eq(xpCurve({max_player_level:2,exp_curve_max_level:2,exp_curve_start_level:1,exp_curve_first_level_xp:4503599627370497,exp_curve_default_scale:1,exp_required_per_level:['[level]1[levelEnd][xp]1[xpEnd]']})[1].xp,4503599627370497,'Java Math.round matches large odd safe integer');
const pack=clone(DEFAULTS);pack['config/ras/templates.json'].warrior={attribute_99:1};eq(validatePack(pack).errors.some(x=>x.msg.includes('unresolved')),true,'Unknown template attribute blocks export');pack['config/ras/templates.json'].warrior={attribute_1:1000};eq(validatePack(pack).errors.some(x=>x.msg.includes('exceeds')),true,'Over-cap template blocks export');pack['config/ras/templates.json'].warrior={attribute_1:1};pack['config/ras/templates.json'].Warrior={attribute_1:2};eq(validatePack(pack).errors.some(x=>x.msg.includes('case-insensitively')),true,'Template names checked without case');delete pack['config/ras/templates.json'].Warrior;pack['config/ras/templates.json'].warrior={'Vitality : ':1};eq(validatePack(pack).errors.length,0,'Actual display-name alias resolves');delete pack['config/ras/attributes/attribute_1.json'];eq(validatePack(pack).warnings.some(x=>x.msg.includes('initializer defaults')),true,'Missing seeded default attribute is explicitly inferred');pack['config/ras/settings.json'].validation_mode='strict';eq(validatePack(pack).warnings.some(x=>x.msg.includes('does not abort')),true,'Strict is not presented as enforcing startup failure');
eq(xpCurve({max_player_level:'bad',exp_curve_scale_intervals:{},exp_required_per_level:null})[0].xp,1,'Malformed field values do not crash preview');
assert.throws(()=>parseJson('{"x":'+ '['.repeat(65)+'0'+']'.repeat(65)+'}'),/nesting/);checks++;
const original=' {\n  \"known\": 1, \"precise_extension\": 0.10000000000000001,\n  \"extension\": {\"a\": [3,1,2]}\n}\n';const parsed=parseJson(original);parsed.known=2;const patched=patchRootJson(original,parsed,new Set(['known']));eq(patched.includes('0.10000000000000001'),true,'Unknown precision lexeme preserved on known root edit');eq(parseJson(patched).known,2,'Edited known field patched correctly');parsed.added=true;eq(parseJson(patchRootJson(original,parsed,new Set(['known','added']))).added,true,'Root missing key appended safely');delete parsed.known;const removed=patchRootJson(original,parsed,new Set(['known']));eq(Object.hasOwn(parseJson(removed),'known'),false,'Deleted root key removed without duplicate comma');eq(patchRootJson(original,parseJson(original),new Set()),original,'Zero patches preserve complete original text');const optional={multiplier:0,hard:0,max_multiplier:1,priority:2};setOptionalNumber(optional,'multiplier','');eq(Object.hasOwn(optional,'multiplier'),false,'Cleared multiplier omits key rather than setting zero');setOptionalNumber(optional,'hard',' ');eq(Object.hasOwn(optional,'hard'),false,'Cleared difficulty omits key');setOptionalNumber(optional,'max_multiplier','');eq(Object.hasOwn(optional,'max_multiplier'),false,'Cleared armor cap uses default');setOptionalNumber(optional,'priority','');eq(Object.hasOwn(optional,'priority'),false,'Cleared priority uses default');eq(attributePathInfo('config/ras/attributes/attribute_01.json').canonical,false,'Padded numeric attribute remains raw-only');eq(attributePathInfo('config/ras/attributes/attribute_999.json').canonical,false,'Runtime sentinel is not a verified ID');eq(attributePathInfo('config/ras/attributes/attribute_0.json').canonical,true,'Canonical zero is supported');console.log(JSON.stringify({edgeChecks:checks,result:'passed'}));
