const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {readZip} from '../dist/zip.mjs';
const root=path.resolve(new URL('../dist',import.meta.url).pathname),out=path.resolve(new URL('../test-results',import.meta.url).pathname);fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname;const f=path.join(root,pathname==='/'?'index.html':pathname);if(!f.startsWith(root)||!fs.existsSync(f)){res.writeHead(404);return res.end('missing')}const ext=path.extname(f);res.writeHead(200,{'content-type':ext==='.mjs'?'text/javascript':ext==='.css'?'text/css':ext==='.svg'?'image/svg+xml':'text/html'});res.end(fs.readFileSync(f))});await new Promise(r=>server.listen(4173,'127.0.0.1',r));
const browser=await chromium.launch({...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{}),headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
let checks=0;const results=[],errors=[],external=[];const eq=(a,b,label)=>{assert.deepEqual(a,b,label);checks++;results.push(label)};const context=await browser.newContext({viewport:{width:1440,height:1024},acceptDownloads:true});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4173/')&&!r.url().startsWith('blob:'))external.push(r.url())});
try{
 await page.goto('http://127.0.0.1:4173/');await page.locator('h1').waitFor();eq(await page.locator('h1').innerText(),'Progression','Workspace opens directly on progression');eq(await page.locator('.metric.accent small').innerText(),'4,100 XP · explicit override','Default XP25 follows explicit table');eq(await page.locator('#live-preview').innerText().then(t=>t.includes('36,062 XP')),true,'100/101 discontinuity shown');
 await page.screenshot({path:path.join(out,'desktop-progression.png'),fullPage:true});
 await page.getByRole('button',{name:'HUD & files',exact:false}).click();await page.locator('[data-file="config/ras/stats_display.json"]').click();
 for(const target of ['4.3.0','4.2.6','4.3.0','4.2.6']){await page.locator('#target-version').selectOption(target);const stats=JSON.parse(await page.locator('#raw-editor').inputValue());eq(stats.totals[2].includes(target==='4.3.0'?'Total Attack Speed Bonus':'Total Mana Bonus'),true,'Fresh raw stats follows target '+target)}
 await page.getByRole('button',{name:'Progression',exact:false}).click();
 await page.getByLabel('First requirement',{exact:false}).fill('200');eq(await page.locator('.metric.accent small').innerText(),'4,100 XP · explicit override','Fallback slider edits leave explicit XP unchanged');await page.getByLabel('First requirement',{exact:false}).fill('140');
 await page.getByLabel('Player level cap',{exact:false}).fill('');await page.getByRole('button',{name:'Review export',exact:false}).click();eq(await page.locator('#download-export').isEnabled(),false,'Empty number blocks export');await page.locator('#cancel-export').click();await page.getByLabel('Player level cap',{exact:false}).fill('500');
 await page.getByRole('button',{name:'Attributes',exact:false}).click();await page.getByRole('button',{name:/ATTRIBUTE 2 Attack Power/}).click();eq(await page.locator('.big-stat').innerText(),'5','Attribute preview uses source command parameter');await page.getByLabel('Maximum final value',{exact:false}).fill('4');eq(await page.locator('.inline-note').allTextContents().then(ts=>ts.join(' ').includes('above the cap')),true,'Final value cap is not point cap');await page.getByLabel('Maximum final value',{exact:false}).fill('500');await page.screenshot({path:path.join(out,'desktop-attributes.png'),fullPage:true});
 await page.getByRole('button',{name:'Class templates',exact:false}).click();eq(await page.locator('.empty').innerText().then(t=>t.includes('No templates')),true,'No invented seeded class templates');await page.getByRole('button',{name:'New template',exact:false}).click();await page.locator('#template-name').fill('warrior');await page.locator('#create-template').click();await page.locator('[data-template-id="attribute_1"]').fill('10');await page.locator('[data-template-id="attribute_2"]').fill('5');eq(await page.locator('.big-stat').innerText(),'15','Template records allocated points');
 await page.getByRole('button',{name:'Mob rewards',exact:false}).click();eq(await page.locator('.result-total strong').innerText(),'20','Legacy reward path with default rate');await page.getByRole('button',{name:'Add rule',exact:false}).click();await page.locator('[data-mob-key="enabled"]').check();eq(await page.locator('.result-total strong').innerText(),'40','Entity base reward before rates');await page.locator('[data-weight="difficulty_weighting"][data-weight-key="enabled"]').check();await page.locator('[data-weight-key="hard"]').fill('2');await page.locator('[data-sample="difficulty"]').selectOption('hard');await page.locator('[data-weight="armor_weighting"][data-weight-key="enabled"]').check();await page.locator('[data-weight-key="per_armor_point"]').fill('0.1');eq(await page.locator('.result-total strong').innerText(),'96','Difficulty and armor weights combine in preview');
 await page.screenshot({path:path.join(out,'desktop-mob-rewards.png'),fullPage:true});
 await page.locator('#target-version').selectOption('4.3.0');eq(await page.locator('.preview-banner').innerText().then(t=>t.includes('not released')),true,'Development target clearly marked unreleased');await page.locator('#export-button').click();eq(await page.locator('#download-export').isEnabled(),true,'Verified development export is enabled');const dl=page.waitForEvent('download');await page.locator('#download-export').click();const download=await dl;const dp=path.join(out,'ui-development-export.zip');await download.saveAs(dp);const files=await readZip(fs.readFileSync(dp));const mob=JSON.parse(new TextDecoder().decode(files['config/ras/mob_xp.json']));eq(mob.rules[0].base_xp,40,'UI ZIP contains actual development rule');eq(mob.difficulty_weighting.hard,2,'UI ZIP carries weight edits');eq(JSON.parse(new TextDecoder().decode(files['config/ras/stats_display.json'])).totals[2].includes('Total Attack Speed Bonus'),true,'Fresh UI development ZIP uses current stats label');const templates=JSON.parse(new TextDecoder().decode(files['config/ras/templates.json']));eq(templates.warrior.attribute_1,10,'Template export schema is top-level actual form');
 await page.locator('#target-version').selectOption('4.2.6');await page.locator('#export-button').click();const stableDL=page.waitForEvent('download');await page.locator('#download-export').click();const stable=await stableDL;const sp=path.join(out,'ui-stable-export.zip');await stable.saveAs(sp);const stableFiles=await readZip(fs.readFileSync(sp));eq(Object.hasOwn(stableFiles,'config/ras/mob_xp.json'),false,'Released export excludes development file');eq(JSON.parse(new TextDecoder().decode(stableFiles['config/ras/stats_display.json'])).totals[2].includes('Total Mana Bonus'),true,'Fresh UI released ZIP keeps historical stats label');
 // Real chooser import, role distinction, text preservation, and unknown fields.
 const imported='{\n  "max_player_level": 12, "exp_curve_max_level": 12,\n  "custom_extension": {"order": [3, 1, 2], "text": "<img src=x onerror=alert(1)>"}\n}\n';const ip=path.join(out,'settings.json');fs.writeFileSync(ip,imported);await page.locator('#file-input').setInputFiles(ip);await page.locator('#import-path').waitFor();eq(await page.locator('#import-path option').count(),3,'settings.json import asks correct file role');await page.locator('#apply-import').click();await page.locator('#export-button').click();const nd=page.waitForEvent('download');await page.locator('#download-export').click();const noEdit=await nd;const np=path.join(out,'untouched-import-export.zip');await noEdit.saveAs(np);const nf=await readZip(fs.readFileSync(np));eq(new TextDecoder().decode(nf['config/ras/settings.json']),imported,'Untouched JSON preserved byte-for-byte');
 await page.getByRole('button',{name:'Progression',exact:false}).click();await page.getByLabel('Player level cap',{exact:false}).fill('15');await page.locator('#export-button').click();const editedD=page.waitForEvent('download');await page.locator('#download-export').click();const edited=await editedD;const ep=path.join(out,'edited-import-export.zip');await edited.saveAs(ep);const ef=await readZip(fs.readFileSync(ep));const eObj=JSON.parse(new TextDecoder().decode(ef['config/ras/settings.json']));eq(eObj.custom_extension,JSON.parse(imported).custom_extension,'Unknown object and ordered array preserved after known edit');eq(await page.locator('img').count(),0,'Imported markup is never rendered as HTML');
 const duplicate=path.join(out,'duplicate.json');fs.writeFileSync(duplicate,'{"a":1,"a":2}');await page.locator('#file-input').setInputFiles(duplicate);await page.getByRole('heading',{name:'Import stopped'}).waitFor();eq(await page.locator('#modal-content').innerText().then(t=>t.includes('Duplicate JSON key')),true,'Duplicate JSON input rejects without workspace changes');await page.locator('[data-close]').click();
 // Malformed but valid JSON root must not crash the editor.
 const malformed=path.join(out,'settings.json');fs.writeFileSync(malformed,'{"max_player_level":"oops","exp_curve_scale_intervals":{},"exp_required_per_level":null}');await page.locator('#file-input').setInputFiles(malformed);await page.locator('#apply-import').click();eq(await page.locator('h1').innerText(),'Progression','Malformed field types stay editable without crashing');await page.locator('#export-button').click();eq(await page.locator('#download-export').isEnabled(),false,'Malformed field types block safe export');await page.locator('#cancel-export').click();
 await page.locator('#reset-button').click();await page.locator('#confirm').click();
 await page.getByRole('button',{name:'HUD & files',exact:false}).click();await page.locator('[data-file="config/ras/stats_display.json"]').click();await page.locator('#target-version').selectOption('4.3.0');const statsEdit=JSON.parse(await page.locator('#raw-editor').inputValue());statsEdit.header_color='#123456';const statsText=JSON.stringify(statsEdit,null,2)+'\n';await page.locator('#raw-editor').fill(statsText);await page.getByRole('button',{name:'Apply JSON changes',exact:true}).click();
 for(const target of ['4.2.6','4.3.0']){await page.locator('#target-version').selectOption(target);eq(await page.locator('#raw-editor').inputValue(),statsText,'Applied raw stats stays exact across target '+target)}
 await page.locator('#reset-button').click();await page.locator('#confirm').click();eq(await page.locator('#target-version').inputValue(),'4.2.6','Fresh defaults reset restores released target');await page.locator('[data-file="config/ras/stats_display.json"]').click();eq(JSON.parse(await page.locator('#raw-editor').inputValue()).totals[2].includes('Total Mana Bonus'),true,'Fresh defaults reset restores historical stats');await page.locator('#target-version').selectOption('4.3.0');eq(JSON.parse(await page.locator('#raw-editor').inputValue()).totals[2].includes('Total Attack Speed Bonus'),true,'Reset stats receives development delta again');await page.locator('#target-version').selectOption('4.2.6');
 // Mobile actual rendered layout and all core sections.
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,deviceScaleFactor:1,hasTouch:true});const mp=await mobile.newPage();mp.on('pageerror',e=>errors.push('mobile: '+e.message));await mp.goto('http://127.0.0.1:4173/');await mp.locator('h1').waitFor();eq(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Mobile progression has no horizontal overflow');await mp.screenshot({path:path.join(out,'mobile-progression.png'),fullPage:true});for(const name of ['Attributes','Mob rewards','Class templates','HUD & files']){await mp.getByRole('button',{name,exact:false}).click();eq(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Mobile '+name+' has no horizontal overflow')}await mp.screenshot({path:path.join(out,'mobile-hud-files.png'),fullPage:true});await mobile.close();
 // Larger text/browser layout approximation at 200% scale: narrow working viewport.
 await page.setViewportSize({width:720,height:1024});await page.getByRole('button',{name:'Progression',exact:false}).click();eq(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Compact desktop layout has no overflow');
 eq(errors,[],'No runtime console exceptions');eq(external,[],'All config processing requests stay local');fs.writeFileSync(path.join(out,'ui-results.json'),JSON.stringify({checks,results,pageErrors:errors,externalRequests:external,source:'Actual local static dist source only. A passing result verifies the listed rendered checks; it does not verify any separately hosted Site, game runtime, or loader build.'},null,2));console.log(JSON.stringify({checks,result:'passed',screenshots:5}));
}finally{await browser.close();await new Promise(r=>server.close(r))}
